# Generated by Django 3.2.4 on 2021-06-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_footerctasettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterCTASettings',
        ),
    ]
